name: dragonfly films
favicon: null
layout_spectrum: 0.53746
typography_spectrum: 0.47897
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050706'
    - '#fcfefd'
    - '#00c8b1'
    - '#2a8446'
    - '#5fbc56'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
