name: dragonflyfilms
favicon: null
layout_spectrum: 0.98962
typography_spectrum: 0.47897
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090b08'
    - '#fffdf7'
    - '#e8e84f'
    - '#24684e'
    - '#58a842'
  brandStrength: 0.1875
  lightness: 0.125
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
