name: dragonfly films
favicon: null
layout_spectrum: 0.66052
typography_spectrum: 0.57149
title: dragonfly films
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#74b4cd'
    - '#1b1b19'
    - '#01698c'
    - '#ffa93a'
    - '#964212'
  brandStrength: 0.0625
  lightness: 0.8125
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
