name: dragonfly films
favicon: null
layout_spectrum: 0.74368
typography_spectrum: 0.57564
title: dragonfly films
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050706'
    - '#fcfefd'
    - '#00c8b1'
    - '#2a8446'
    - '#5fbc56'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
