name: dragonfly films
favicon: null
layout_spectrum: 0.65845
typography_spectrum: 0.57149
title: dragonfly films
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fee703'
    - '#050704'
    - '#fefdf8'
    - '#1b4e47'
    - '#7b8121'
  brandStrength: 0.25
  lightness: 0.8125
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
