name: dragonfly films
favicon: null
layout_spectrum: 0.58739
typography_spectrum: 0.57149
title: dragonfly films
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2ca2f6'
    - '#6b69bb'
    - '#9492d4'
    - '#82c2eb'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
